package eisbw;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Danny & Harm - The windowstool for starting the chaoslauncher and
 *         writing the menu script.
 *
 */
public class WindowsTools {
	private WindowsTools() {
		// Private constructor to hide the public one.
	}

	/**
	 * Starts the Chaoslauncher with launch rules.
	 *
	 * @param race
	 *            the race specified in the mas2g
	 * @param map
	 *            the map specified in the mas2g
	 * @param scDir
	 *            the starcraft installation directory in the mas2g.
	 * @param autoMenu
	 *            the automenu (single- or multi-player) specified in the mas2g
	 * @param enemyRace
	 *            the enemy race
	 * @param seed
	 *            the seed (overrides the game seed if > 0)
	 * @throws IOException
	 *             throws exception when BWAPI.ini cannot be written.
	 */
	public static void startChaoslauncher(String race, String map, String scDir, String autoMenu, String gameType,
			String enemyRace, int seed) throws IOException {
		if (!scDir.endsWith("\\")) {
			scDir = scDir + "\\";
		}
		populateInitFile(race, map, scDir, autoMenu, gameType, enemyRace, seed);
		Client_InitialSetup(scDir);
		if (autoMenu.toLowerCase().equals("lan")) {
			Runtime.getRuntime().exec(new String[] { scDir + "Chaoslauncher\\Chaoslauncher - MultiInstance.exe" }, null,
					new File(scDir + "Chaoslauncher\\"));
		} else {
			Runtime.getRuntime().exec(scDir + "Chaoslauncher\\Chaoslauncher.exe", null,
					new File(scDir + "Chaoslauncher\\"));
		}
	}

	private static void populateInitFile(String race, String map, String scDir, String autoMenu, String gameType,
			String enemyRace, int seed) {
		String bwapiDest = scDir + "bwapi-data\\bwapi.ini";
		String iniFile = getIniFile(race, map, autoMenu, gameType, enemyRace, seed);
		try {
			BufferedWriter out = new BufferedWriter(new FileWriter(new File(bwapiDest)));
			out.write(iniFile);
			out.close();
		} catch (Exception exception) {
			Logger.getLogger("StarCraft Logger").log(Level.SEVERE, "Could not write config file.", exception);
		}
	}

	protected static String getIniFile(String race, String map, String autoMenu, String gameType, String enemyRace,
			int seed) {
		String newLine = System.getProperty("line.separator");
		String iniFile = "";
		iniFile += ";Generated by the GOAL-StarCraft connector" + newLine;

		iniFile += "[ai]" + newLine;
		iniFile += "ai     = NULL" + newLine + newLine;

		iniFile += "[auto_menu]" + newLine;
		iniFile += "auto_menu = " + autoMenu + newLine;
		iniFile += "game_type = " + gameType + newLine;
		if (autoMenu.toLowerCase().equals("lan")) {
			iniFile += "lan_mode = local pc" + newLine;
		}
		iniFile += "pause_dbg = OFF" + newLine;
		iniFile += "auto_restart = OFF" + newLine;
		iniFile += "map = maps\\" + map + newLine;
		iniFile += "race = " + race + newLine;
		iniFile += "enemy_count = 1" + newLine;
		iniFile += "enemy_race = " + enemyRace + newLine + newLine;

		iniFile += "[config]" + newLine;
		iniFile += "holiday = OFF" + newLine;
		iniFile += "shared_memory = ON" + newLine + newLine;

		iniFile += "[window]" + newLine;
		iniFile += "windowed = ON" + newLine;
		iniFile += "width  = 1024" + newLine;
		iniFile += "height = 768" + newLine + newLine;

		iniFile += "[starcraft]" + newLine;
		iniFile += "sound = ON" + newLine;
		if (seed > 0) {
			iniFile += "seed_override = " + Integer.toString(seed) + newLine;
		}
		return iniFile;
	}

	protected static String getRace(String race, int seed) {
		if (race.equals("randomtp")) {
			Random random = (seed > 0) ? new Random(seed) : new Random();
			return (random.nextInt(2) == 0) ? "terran" : "protoss";
		} else if (race.equals("randomtz")) {
			Random random = (seed > 0) ? new Random(seed) : new Random();
			return (random.nextInt(2) == 0) ? "terran" : "zerg";
		} else if (race.equals("randompz")) {
			Random random = (seed > 0) ? new Random(seed) : new Random();
			return (random.nextInt(2) == 0) ? "protoss" : "zerg";
		} else {
			return race;
		}
	}

	private static void Client_InitialSetup(String scPath) {
		// Make sure Starcraft isn't running
		Client_KillStarcraft();
		// Set up local firewall access
		RunWindowsCommand("netsh firewall add allowedprogram program = " + scPath
				+ "starcraft.exe name = Starcraft mode = ENABLE scope = ALL");
		// Make sure all Starcraft and Chaoslauncher settings are correct
		Client_RegisterStarCraft(scPath);
	}

	private static void Client_RegisterStarCraft(String scPath) {
		// 32-bit machine StarCraft settings
		String sc32KeyName = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Blizzard Entertainment\\Starcraft";
		String sc32UserKeyName = "HKEY_CURRENT_USER\\SOFTWARE\\Blizzard Entertainment\\Starcraft";
		RegEdit(sc32KeyName, "InstallPath", "REG_SZ", scPath + "\\");
		RegEdit(sc32KeyName, "Program", "REG_SZ", scPath + "StarCraft.exe");
		RegEdit(sc32KeyName, "GamePath", "REG_SZ", scPath + "StarCraft.exe");
		RegEdit(sc32UserKeyName, "introX", "REG_DWORD", "00000000");
		// 64-bit machine StarCraft settings
		String sc64KeyName = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Blizzard Entertainment\\Starcraft";
		String sc64UserKeyName = "HKEY_CURRENT_USER\\SOFTWARE\\Wow6432Node\\Blizzard Entertainment\\Starcraft";
		RegEdit(sc64KeyName, "InstallPath", "REG_SZ", scPath + "\\");
		RegEdit(sc64KeyName, "Program", "REG_SZ", scPath + "StarCraft.exe");
		RegEdit(sc64KeyName, "GamePath", "REG_SZ", scPath + "StarCraft.exe");
		RegEdit(sc64UserKeyName, "introX", "REG_DWORD", "00000000");
		// Chaoslauncher Settings
		String clKeyName = "HKEY_CURRENT_USER\\Software\\Chaoslauncher\\Launcher";
		RegEdit(clKeyName, "GameVersion", "REG_SZ", "Starcraft 1.16.1");
		RegEdit(clKeyName, "Width", "REG_DWORD", "00000640");
		RegEdit(clKeyName, "Height", "REG_DWORD", "00000480");
		RegEdit(clKeyName, "StartMinimized", "REG_SZ", "0");
		RegEdit(clKeyName, "MinimizeOnRun", "REG_SZ", "1");
		RegEdit(clKeyName, "RunScOnStartup", "REG_SZ", "1");
		RegEdit(clKeyName, "AutoUpdate", "REG_SZ", "0");
		RegEdit(clKeyName, "WarnNoAdmin", "REG_SZ", "0");
		// Chaoslauncher plugin settings
		String clpKeyName = "HKEY_CURRENT_USER\\Software\\Chaoslauncher\\PluginsEnabled";
		RegEdit(clpKeyName, "BWAPI Injector (1.16.1) RELEASE", "REG_SZ", "1");
		RegEdit(clpKeyName, "W-MODE 1.02", "REG_SZ", "1");
		/* RegEdit(clpKeyName, "Chaosplugin for 1.16.1", "REG_SZ", "0"); */
	}

	public static void Client_KillStarcraft() {
		while (IsWindowsProcessRunning("StarCraft.exe")) {
			RunWindowsCommand("taskkill /T /F /IM StarCraft.exe");
			try {
				Thread.sleep(100);
			} catch (InterruptedException ignore) {
			}
		}
		while (IsWindowsProcessRunning("Chaoslauncher.exe")) {
			RunWindowsCommand("taskkill /T /F /IM Chaoslauncher.exe");
			try {
				Thread.sleep(100);
			} catch (InterruptedException ignore) {
			}
		}
		while (IsWindowsProcessRunning("\"Chaoslauncher - MultiInstance.exe\"")) {
			RunWindowsCommand("taskkill /T /F /IM \"Chaoslauncher - MultiInstance.exe\"");
			try {
				Thread.sleep(100);
			} catch (InterruptedException ignore) {
			}
		}
	}

	private static boolean IsWindowsProcessRunning(String process) {
		try {
			Process p = Runtime.getRuntime().exec("tasklist.exe");
			try (BufferedReader stdInput = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
				String line;
				while ((line = stdInput.readLine()) != null) {
					if (line.contains(process)) {
						return true;
					}
				}
			}
		} catch (Exception e) {
			Logger.getLogger("StarCraft Logger").log(Level.SEVERE, "IsWindowsProcessRunning " + process, e);
		}

		return false;
	}

	private static void RunWindowsCommand(String command) {
		try {
			String windowsCommandPrefix = "CMD /C ";
			Process proc = Runtime.getRuntime().exec(windowsCommandPrefix + command);
			proc.waitFor();
		} catch (Exception e) {
			Logger.getLogger("StarCraft Logger").log(Level.SEVERE, "RunWindowsCommand " + command, e);
		}
	}

	private static void RegEdit(String keyName, String valueName, String type, String data) {
		String q = "\"";
		// make sure there are no quotations in the input strings
		keyName.replaceAll(q, "");
		valueName.replaceAll(q, "");
		type.replaceAll(q, "");
		data.replaceAll(q, "");
		// wrap quotations around the values to be sure
		keyName = q + keyName + q;
		valueName = q + valueName + q;
		data = q + data + q;
		// run the command
		RunWindowsCommand("reg add " + keyName + " /f /v " + valueName + " /t " + type + " /d " + data);
	}
}
